### ISSUE TITLE
Unenroll button not working.

### ISSUE THREAD

**Issue by Sharmakunjan** [Green-Haven-Hostel/Hostel-Management-System#11]
By Clicking Enroll button. the user name from enroll table should be removed .

**Comment by SujanPrasadPandey** [comment]
#12 is fixed! @Sharmakunjan View this PR, which resolves the problem.

**Comment by Sharmakunjan** [comment]
Great work on addressing issue #12! I've reviewed the PR and it looks good. Thank you for your effort!
