### ISSUE TITLE
Feedback is not showing(User)

### ISSUE THREAD

**Issue by Sharmakunjan** [Green-Haven-Hostel/Hostel-Management-System#14]
The Feedback Questions is not displaying on user's page.

**Comment by RoshanKumarYadav11** [comment]
I've resolved this issue in PR #16  kindly refer to it @Sharmakunjan.

**Comment by Sharmakunjan** [comment]
Thank you for the update! I have reviewed PR #16 and can confirm that the issue has been successfully resolved
