### ISSUE TITLE
The php file is not connected with MySQL database. 

### ISSUE THREAD

**Issue by Sharmakunjan** [Green-Haven-Hostel/Hostel-Management-System#2]
To resolve the issue, you should:

Check the connection code in your PHP file and ensure it is correct.
Verify that the MySQL server is running and accessible from the host where the PHP script is executing.
Confirm that the PHP extensions for MySQL (e.g., mysqli or PDO) are installed and enabled.
Troubleshoot any network or firewall issues that may be preventing the connection.

**Comment by SujanPrasadPandey** [comment]
I'm pleased to inform that the issue with the PHP file not connecting to the MySQL database has been resolved. After thorough investigation, I have identified and corrected the root cause
