### ISSUE TITLE
Not showing Access log of users to Admin

### ISSUE THREAD

**Issue by Sharmakunjan** [Green-Haven-Hostel/Hostel-Management-System#3]
There is an issue with the access log of users not displaying for the admin. To address this, we'll need to investigate further. Here's what we'll do:

Review Access Log Functionality: We'll check the functionality responsible for displaying the access log to ensure it is correctly implemented.
Database Query: We'll verify that the database query used to fetch the access log data is correct and retrieves the information for the admin to view.
Check Permissions: We'll ensure that the admin user has the necessary permissions to view the access log. This includes checking the user roles and access levels in the system.
Debugging: If necessary, we'll use debugging techniques to identify any specific errors or issues that are preventing the access log from displaying.

**Comment by RoshanKumarYadav11** [comment]
I'm pleased to inform you that the issue with the access log not displaying for the admin has been resolved.  Please verify that you can now see the access log information. If you encounter any further issues or have any questions, feel free to reach out.
