### ISSUE TITLE
Remove course section && Refactor that with Event registration.

### ISSUE THREAD

**Issue by Sharmakunjan** [Green-Haven-Hostel/Hostel-Management-System#6]
In this new section, administrators will be able to add events, including details such as event name, date, location, and description. Users will then be able to enroll in these events. The section will display a list of upcoming events, and users can select an event to enroll.

**Comment by SujanPrasadPandey** [comment]
#12 is fixed! @Sharmakunjan View this PR, which resolves the problem.

**Comment by Sharmakunjan** [comment]
Great work on addressing issue https://github.com/Green-Haven-Hostel/Hostel-Management-System/pull/12! I've reviewed the PR and it looks good. Thank you for your effort!
