### ISSUE TITLE
Add New Event. 

### ISSUE THREAD

**Issue by Sharmakunjan** [Green-Haven-Hostel/Hostel-Management-System#7]
The add button is not working. The event cannot be added by the admin.

**Comment by SujanPrasadPandey** [comment]
#12 is fixed! @Sharmakunjan View this PR, which resolves the problem.

**Comment by Sharmakunjan** [comment]
Great work on addressing issue https://github.com/Green-Haven-Hostel/Hostel-Management-System/pull/12! I've reviewed the PR and it looks good. Thank you for your effort!
