### ISSUE TITLE
Not Fetching Data.

### ISSUE THREAD

**Issue by Sharmakunjan** [Green-Haven-Hostel/Hostel-Management-System#9]
Graph is not displaying  the total status of the room allocation, feedback analysis by the admin.

**Comment by sugampathak11** [comment]
#17 i have fixed this issue @Sharmakunjan !! please review it

**Comment by Sharmakunjan** [comment]
Thank you for the update! I have reviewed PR https://github.com/Green-Haven-Hostel/Hostel-Management-System/pull/17 and can confirm that the issue has been successfully resolved
